### ISSUE TITLE
Fix prop rotation

### ISSUE THREAD

**Issue by Yami07** [MrCraigTunstall/zombiesurvival#101]
If you rotate a prop like a heavy one most of the time your prop wouldnt even rotate resulting in caders having to throw the prop down and re attempt but even after doing this it wouldnt rotate, any fix??

**Comment by MrCraigTunstall** [comment]
https://github.com/MrCraigTunstall/zombiesurvival/commit/d27c7b9de6eabd84127870a4d4ff60cd1a92a10b

**Comment by besenyei** [comment]
Does this fix big couches halting rotation when you rotate them too fast?
