### ISSUE TITLE
Music/beat ideas that could improve the audiovisual experience

### ISSUE THREAD

**Issue by Gabipie** [MrCraigTunstall/zombiesurvival#43]
Perhaps add infliction music? For example music could start playing for everyone when infliction reaches 0.5 or 0.75. I was thinking that should be fairly easy to implement.
I also had in mind that a ''randomizer'' for last human music would be great too, just throw in a few songs and one of them would play at random, that way you wouldn't always get the same last human song over and over.
I also think adding custom boss music would be great, music that would only play of course when the boss is anywhere near the human team, similar to how the default Zs beats work.
Possibly beats/music that only plays after an X amount of your human comrades gets slaughtered by the undead horde would be great too. Adding a config for each of those wouldn't be too bad either, it would surely allow it all to sound smoother and allow proper customization.

**Comment by kay-33** [comment]
i have noticed some sound play on same time and make it horrible :o,, if you can make somting for :D
