### ISSUE TITLE
make tab in setting windows

### ISSUE THREAD

**Issue by kay-33** [MrCraigTunstall/zombiesurvival#50]
I guess is will be more comfortable to get in setting something like "tab", one for gui, sound ,and other :D

**Comment by MrCraigTunstall** [comment]
we're already working on it.

**Comment by MrCraigTunstall** [comment]
Started such system https://github.com/MrCraigTunstall/zombiesurvival/commit/074f94808a3fbcf2616a8a7c38c5bf54528ccea4
