### ISSUE TITLE
Force field issue 

### ISSUE THREAD

**Issue by Yami07** [MrCraigTunstall/zombiesurvival#54]
Humans cannot shoot out of the force field which creates a question in mind on how they are supposed to defend the cade ???? Make it so you have to add a certain type of ammo to the field emitter to keep it going

**Comment by Flairieve** [comment]
Sounds like a fix is needed for that. Also I'm not sure if it should use ammo as having a health bar on it seems more simple. Maybe an energy system can be added in for tools that use energy?

**Comment by kay-33** [comment]
I suggest only fire with energy weapon :D and maybe make more easy to break it for zombie ,like if to many zombie attack it is will explode.
