### ISSUE TITLE
New cading mechanic/joe nails are displayed

### ISSUE THREAD

**Issue by Yami07** [MrCraigTunstall/zombiesurvival#61]
More nails into a prop gives it more health and more repair 
Make it show the nail HP and the amount that you can repair in the middle of the prop so players can see it clearly+easier to read without having to press shift to read nail hp

**Comment by Yami07** [comment]
How nails are displayed*

**Comment by Flairieve** [comment]
Prop HP in the middle of the prop might be distracting so to see the total amount of health on the prop I think I will make it where they need to press shift as it can get distracting.

**Comment by Yami07** [comment]
So would more nails in the prop be worked on for future updates ?

**Comment by Yami07** [comment]
More nails into a prop increase it’s hp be worked on ?*

**Comment by kay-33** [comment]
Many a cover for only allowed to remove nail of other player was dead ?

**Comment by Yami07** [comment]
If this is going to be added make props have nude 700 hp for starting without 1+++ nails added

**Comment by Yami07** [comment]
Less than *

**Comment by Flairieve** [comment]
I guess unlimited nails on a prop sounds like a good idea?

**Comment by Yami07** [comment]
Can only put 4 nails into a prop

**Comment by MrCraigTunstall** [comment]
https://github.com/MrCraigTunstall/zombiesurvival/commit/a0aac8beb7dbac557ba6f8a4bc1d7b577918e4f9
