### ISSUE TITLE
Rebirth or remort 

### ISSUE THREAD

**Issue by Yami07** [MrCraigTunstall/zombiesurvival#63]
After level 50 or 100 you can remort this will help with new players or if your a elder player on the server

**Comment by Flairieve** [comment]
I don't think this gamemode actually has the xp system? I think that's on the server itself?

**Comment by Yami07** [comment]
Yea I made this ticket for the server , so once you hit level 50 in game it can show a 1 or a 2 depending how much times you have gotten to level 50
