### ISSUE TITLE
Speed or Quick

### ISSUE THREAD

**Issue by Yami07** [MrCraigTunstall/zombiesurvival#65]
This item can be purchased in the arsenal crate during waves , will get you inside cades faster, im seeing a lot of players having issues with getting into cades that are very thick.This would allow it for players to get into cades faster which is very useful

**Comment by MrCraigTunstall** [comment]
I had an update that should fix "cade lag". Do you mean as moving into cades faster as an overall system?

**Comment by MrCraigTunstall** [comment]
Added Ghost Mode Trait -- You can ghost through props much faster
https://github.com/MrCraigTunstall/zombiesurvival/commit/73aa9430f917c6870a121bde6b420bb3c07f8d2a
