### ISSUE TITLE
Sigil placements

### ISSUE THREAD

**Issue by Yami07** [MrCraigTunstall/zombiesurvival#70]
Please place sigils in areas that humans can actually defend instead of using the sigil placer and marking everywhere on the map with red this would just make it easier for humans

**Comment by MrCraigTunstall** [comment]
I have been doing that. Please state which maps, thanks.

**Comment by Yami07** [comment]
zs_anartichouse

**Comment by Yami07** [comment]
A and B were literally cade blocked

**Comment by Yami07** [comment]
Zs_asylum
