### ISSUE TITLE
Skill tree 

### ISSUE THREAD

**Issue by Yami07** [MrCraigTunstall/zombiesurvival#73]
Skill tree unlock points for you to use to upgrade or get health,etc 
Level 1- 1point
Level 2- 1point..etc 
The skill tree can include 
+1health (.05 speed decrease)
+2 health (1.0 speed decrease) 
...etc 
Speed: 
+1.05 speed increase ( 2 hp decrease) 
+1.50 speed increase (3 hp decrease) 
...etc
Cading 
+5% swing delay 
+10% health repaired 
+15% health repaired 
...etc feel free to comment more things to add or fix

**Comment by Flairieve** [comment]
Sounds nice!

**Comment by MrCraigTunstall** [comment]
Won't add nox skill tree but might add our own type.
