### ISSUE TITLE
Make it possible to see nails through props as human+make it possible to see nail hp as zombie

### ISSUE THREAD

**Issue by Yami07** [MrCraigTunstall/zombiesurvival#81]
https://steamuserimages-a.akamaihd.net/ugc/2419999249755637895/4157EF7EBD0E8F19D86F45C8D386A0958F235D3C/ 
This will show you what i mean , make it so humans can see the nails through props it would make it easier to tell which props i need to repair without moving around to look at them.
As for zombie , it would make sense to see how much damage im doing to the cade and see if im getting near to it breaking

**Comment by Flairieve** [comment]
Maybe highlighting the nail when holding down shift will fix this. Also how can zombies know the health of a cade if they don't have brains?

**Comment by Yami07** [comment]
Yea but I don’t want to hold shift while repairing I’m wondering if there’s a easier fix for this so I can see the HP without holding shift+moving around locations

**Comment by MrCraigTunstall** [comment]
https://github.com/MrCraigTunstall/zombiesurvival/commit/3e16f7f49956fb61f2f15b8dc8e6d11efd3d6b74

HP is coming soon hopefully.
