### ISSUE TITLE
Upgrade of zombies

### ISSUE THREAD

**Issue by kay-33** [MrCraigTunstall/zombiesurvival#87]
-Fast zombie  that it moves less quickly when he attack and that he does 5 of damages and that he can attack during jump with "bar space".
- Boost the poison zombie by making it move (slowly enough) by sending poison
- Boost crab poison he can move slowly when he pulls a ball and he can move the camera when he wants to jump.
- Make sure that the zombie torso and all the crabs can jump a minimum with the "bar space".
- When we take a ball of poison in the head we see nothing it would be nice if we see a little otherwise unplayable.
 - Decrease the attack range of the Zombie, Ghoul, Zombie Balloon, Zombin, Zombie Poison, and Optionally the Nightmare (unless it causes problems with bot levels).

^w^

**Comment by Yami07** [comment]
Sounds good

**Comment by Flairieve** [comment]
Sounds like a good idea!
