### ISSUE TITLE
Fix sigil teleporting 

### ISSUE THREAD

**Issue by TheFray89** [MrCraigTunstall/zombiesurvival#91]
When you press e on a sigil, most of the time you dont teleport and when it works takes extremely long time (more than 10 seconds)

**Comment by MrCraigTunstall** [comment]
A fix plus many other updates to do with the sigils are coming. It will be updated in one whole push. The latest fixes and improvements are worth the wait.

**Comment by MrCraigTunstall** [comment]
https://github.com/MrCraigTunstall/zombiesurvival/pull/96/commits/bdd35b689f6f763e083ef7212892c47151c06798
